layout_head:
  embedding_dim: 1024
  hidden_dim: 512
  num_hidden_layers: 2
  dropout: 0.1
  loss: smooth_l1
  beta: 0.1
  learning_rate: 0.001
  batch_size: 32
  epochs: 5
  val_fraction: 0.1
  random_seed: 13
  dataset:
    split: train
    cache_dir: ${HF_HOME:-~/.cache/huggingface}
    embedding_store: null
    allow_random: true
    dataset_limit: 2048
  outputs:
    artifacts_dir: layout/artifacts
    metrics_path: layout/artifacts/layout_head_metrics.json

classifier:
  embedding_dim: 1024
  use_layout: true
  train:
    cli: triage/triage/train_rvl_classifier.py
    output_dir: triage/artifacts
    checkpoint: triage/artifacts/rvl_classifier.pt
    logits: triage/artifacts/rvl_val_logits.npz
    metrics: triage/artifacts/rvl_training_metrics.json
    dry_run: true
  eval:
    cli: triage/triage/eval_rvl_classifier.py
    metrics_path: metrics/rvl_classifier.json
    save_logits: triage/artifacts/rvl_val_logits.npz

calibration:
  temperature_cli: triage/calibration/fit_temperature.py
  evaluation_cli: triage/calibration/evaluate_calibration.py
  temperature_path: triage/artifacts/calibration_temp.json
  metrics_path: metrics/calibration.json
  thresholds: [0.9, 0.95, 0.97, 0.99]
  plot_dir: reports
  plot_prefix: calibration_reliability

abstention:
  apply_cli: triage/triage/apply_abstention.py
  output: metrics/abstention.json
  tune_cli: scripts/tune_abstention.py
  sweep_output: metrics/abstention_sweep.json
  sweep_plot: reports/abstention_curve.png
  min_coverage: 0.6
